services:
  - type: web
    name: ux-crime-dating-app
    env: node
    plan: free
    buildCommand: npm install --include=dev --prefix frontend && npm install --include=dev --prefix backend && npm run build --prefix frontend
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        sync: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: IMAGEKIT_PUBLIC_KEY
        sync: false
      - key: IMAGEKIT_PRIVATE_KEY
        sync: false
      - key: IMAGEKIT_URL_ENDPOINT
        sync: false
